CREATE DATABASE ayada;
CREATE USER 'ayada'@'%' IDENTIFIED BY 'Sid$osi#123';
GRANT ALL PRIVILEGES ON ayada.* TO 'ayada'@'%' WITH GRANT OPTION;
CREATE DATABASE agaddam;
CREATE USER 'agaddam'@'%' IDENTIFIED BY 'Sid$osi#123';
GRANT ALL PRIVILEGES ON agaddam.* TO 'agaddam'@'%' WITH GRANT OPTION;
CREATE DATABASE aramcherla;
CREATE USER 'aramcherla'@'%' IDENTIFIED BY 'Sid$osi#123';
GRANT ALL PRIVILEGES ON aramcherla.* TO 'aramcherla'@'%' WITH GRANT OPTION;
CREATE DATABASE bbenjaram;
CREATE USER 'bbenjaram'@'%' IDENTIFIED BY 'Sid$osi#123';
GRANT ALL PRIVILEGES ON bbenjaram.* TO 'bbenjaram'@'%' WITH GRANT OPTION;
CREATE DATABASE bkonda;
CREATE USER 'bkonda'@'%' IDENTIFIED BY 'Sid$osi#123';
GRANT ALL PRIVILEGES ON bkonda.* TO 'bkonda'@'%' WITH GRANT OPTION;
CREATE DATABASE bakula;
CREATE USER 'bakula'@'%' IDENTIFIED BY 'Sid$osi#123';
GRANT ALL PRIVILEGES ON bakula.* TO 'bakula'@'%' WITH GRANT OPTION;
CREATE DATABASE ipilli;
CREATE USER 'ipilli'@'%' IDENTIFIED BY 'Sid$osi#123';
GRANT ALL PRIVILEGES ON ipilli.* TO 'ipilli'@'%' WITH GRANT OPTION;
CREATE DATABASE nkethoji;
CREATE USER 'nkethoji'@'%' IDENTIFIED BY 'Sid$osi#123';
GRANT ALL PRIVILEGES ON nkethoji.* TO 'nkethoji'@'%' WITH GRANT OPTION;
CREATE DATABASE pbombothula;
CREATE USER 'pbombothula'@'%' IDENTIFIED BY 'Sid$osi#123';
GRANT ALL PRIVILEGES ON pbombothula.* TO 'pbombothula'@'%' WITH GRANT OPTION;
CREATE DATABASE pmuthepwar;
CREATE USER 'pmuthepwar'@'%' IDENTIFIED BY 'Sid$osi#123';
GRANT ALL PRIVILEGES ON pmuthepwar.* TO 'pmuthepwar'@'%' WITH GRANT OPTION;
CREATE DATABASE rpolasa;
CREATE USER 'rpolasa'@'%' IDENTIFIED BY 'Sid$osi#123';
GRANT ALL PRIVILEGES ON rpolasa.* TO 'rpolasa'@'%' WITH GRANT OPTION;
CREATE DATABASE rgundla;
CREATE USER 'rgundla'@'%' IDENTIFIED BY 'Sid$osi#123';
GRANT ALL PRIVILEGES ON rgundla.* TO 'rgundla'@'%' WITH GRANT OPTION;
CREATE DATABASE rkotte;
CREATE USER 'rkotte'@'%' IDENTIFIED BY 'Sid$osi#123';
GRANT ALL PRIVILEGES ON rkotte.* TO 'rkotte'@'%' WITH GRANT OPTION;
CREATE DATABASE rmuniganti;
CREATE USER 'rmuniganti'@'%' IDENTIFIED BY 'Sid$osi#123';
GRANT ALL PRIVILEGES ON rmuniganti.* TO 'rmuniganti'@'%' WITH GRANT OPTION;
CREATE DATABASE ssurabhi;
CREATE USER 'ssurabhi'@'%' IDENTIFIED BY 'Sid$osi#123';
GRANT ALL PRIVILEGES ON ssurabhi.* TO 'ssurabhi'@'%' WITH GRANT OPTION;
CREATE DATABASE sjillella;
CREATE USER 'sjillella'@'%' IDENTIFIED BY 'Sid$osi#123';
GRANT ALL PRIVILEGES ON sjillella.* TO 'sjillella'@'%' WITH GRANT OPTION;
CREATE DATABASE ssadula;
CREATE USER 'ssadula'@'%' IDENTIFIED BY 'Sid$osi#123';
GRANT ALL PRIVILEGES ON ssadula.* TO 'ssadula'@'%' WITH GRANT OPTION;
CREATE DATABASE smanthaPuri;
CREATE USER 'smanthaPuri'@'%' IDENTIFIED BY 'Sid$osi#123';
GRANT ALL PRIVILEGES ON smanthaPuri.* TO 'smanthaPuri'@'%' WITH GRANT OPTION;
CREATE DATABASE tgorla;
CREATE USER 'tgorla'@'%' IDENTIFIED BY 'Sid$osi#123';
GRANT ALL PRIVILEGES ON tgorla.* TO 'tgorla'@'%' WITH GRANT OPTION;
CREATE DATABASE tkumbam;
CREATE USER 'tkumbam'@'%' IDENTIFIED BY 'Sid$osi#123';
GRANT ALL PRIVILEGES ON tkumbam.* TO 'tkumbam'@'%' WITH GRANT OPTION;
CREATE DATABASE vmegavath;
CREATE USER 'vmegavath'@'%' IDENTIFIED BY 'Sid$osi#123';
GRANT ALL PRIVILEGES ON vmegavath.* TO 'vmegavath'@'%' WITH GRANT OPTION;
CREATE DATABASE vgalipalli;
CREATE USER 'vgalipalli'@'%' IDENTIFIED BY 'Sid$osi#123';
GRANT ALL PRIVILEGES ON vgalipalli.* TO 'vgalipalli'@'%' WITH GRANT OPTION;
CREATE DATABASE rmaduri;
CREATE USER 'rmaduri'@'%' IDENTIFIED BY 'Sid$osi#123';
GRANT ALL PRIVILEGES ON rmaduri.* TO 'rmaduri'@'%' WITH GRANT OPTION;
CREATE DATABASE asabban;
CREATE USER 'asabban'@'%' IDENTIFIED BY 'Sid$osi#123';
GRANT ALL PRIVILEGES ON asabban.* TO 'asabban'@'%' WITH GRANT OPTION;
CREATE DATABASE bnimma;
CREATE USER 'bnimma'@'%' IDENTIFIED BY 'Sid$osi#123';
GRANT ALL PRIVILEGES ON bnimma.* TO 'bnimma'@'%' WITH GRANT OPTION;
CREATE DATABASE sgandhari;
CREATE USER 'sgandhari'@'%' IDENTIFIED BY 'Sid$osi#123';
GRANT ALL PRIVILEGES ON sgandhari.* TO 'sgandhari'@'%' WITH GRANT OPTION;
CREATE DATABASE vrekulapally;
CREATE USER 'vrekulapally'@'%' IDENTIFIED BY 'Sid$osi#123';
GRANT ALL PRIVILEGES ON vrekulapally.* TO 'vrekulapally'@'%' WITH GRANT OPTION;
CREATE DATABASE pbaithi;
CREATE USER 'pbaithi'@'%' IDENTIFIED BY 'Sid$osi#123';
GRANT ALL PRIVILEGES ON pbaithi.* TO 'pbaithi'@'%' WITH GRANT OPTION;
CREATE DATABASE skukatla;
CREATE USER 'skukatla'@'%' IDENTIFIED BY 'Sid$osi#123';
GRANT ALL PRIVILEGES ON skukatla.* TO 'skukatla'@'%' WITH GRANT OPTION;
CREATE DATABASE mchippa;
CREATE USER 'mchippa'@'%' IDENTIFIED BY 'Sid$osi#123';
GRANT ALL PRIVILEGES ON mchippa.* TO 'mchippa'@'%' WITH GRANT OPTION;
CREATE DATABASE snakshatram;
CREATE USER 'snakshatram'@'%' IDENTIFIED BY 'Sid$osi#123';
GRANT ALL PRIVILEGES ON snakshatram.* TO 'snakshatram'@'%' WITH GRANT OPTION;
CREATE DATABASE vnagarajan;
CREATE USER 'vnagarajan'@'%' IDENTIFIED BY 'Sid$osi#123';
GRANT ALL PRIVILEGES ON vnagarajan.* TO 'vnagarajan'@'%' WITH GRANT OPTION;
